# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpGateway < Formula
  desc "Local-first MCP aggregator — k9s for MCP"
  homepage "https://github.com/ayu5h-raj/mcp-gateway"
  version "1.0.0-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.0-rc1/mcp-gateway-macos-intel-v1.0.0-rc1.tar.gz"
      sha256 "4530d5bd0b114af373e47bc61d1a9a1bf83a53758515655f27d180d17d6dbd63"

      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.0-rc1/mcp-gateway-macos-arm64-v1.0.0-rc1.tar.gz"
      sha256 "02c9159ac917bd120139d52725c4dd0344dd09f125b9678143fadc64f85d0de9"

      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.0-rc1/mcp-gateway-linux-intel-v1.0.0-rc1.tar.gz"
      sha256 "6f91f4fc92689bf22e7ac27b5ccfd99cf3808e180a60fecde36a2591d9debb34"
      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.0-rc1/mcp-gateway-linux-arm64-v1.0.0-rc1.tar.gz"
      sha256 "44591325dba921d8f527dff60ec8fe6a2f0c3fe3e6aa555e330e82c0ed07b82a"
      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
  end

  test do
    assert_match "mcp-gateway", shell_output("#{bin}/mcp-gateway --version")
  end
end
