# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpGateway < Formula
  desc "Local-first MCP aggregator — k9s for MCP"
  homepage "https://github.com/ayu5h-raj/mcp-gateway"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.6/mcp-gateway-macos-intel-v1.0.6.tar.gz"
      sha256 "69163ec48a29d67470f0226b94c02b4a6217114447d2b7581e7529d1e9119407"

      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.6/mcp-gateway-macos-arm64-v1.0.6.tar.gz"
      sha256 "df1590cefbb5a0fd7d9afb575ce07985093f3c58c6c694dc79d4969dce62712b"

      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.6/mcp-gateway-linux-intel-v1.0.6.tar.gz"
      sha256 "c1ef5d96482ed1843ba129e8e52271e8e31619cca3caeb3978064efb21e1af64"
      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayu5h-raj/mcp-gateway/releases/download/v1.0.6/mcp-gateway-linux-arm64-v1.0.6.tar.gz"
      sha256 "55e6f82aec6724fdffa3aa397ef8498debb140d655fab7dddd91fe90329b2869"
      define_method(:install) do
        bin.install "mcp-gateway"
        bin.install "mgw-smoke"
      end
    end
  end

  def caveats
    <<~EOS
      First-run wizard (run once):
        mcp-gateway init

      Useful commands:
        mcp-gateway tui              live ops dashboard
        mcp-gateway list             show servers + tool counts
        mcp-gateway service status   inspect the launchd auto-start service

      Uninstall — run in this order:
        mcp-gateway service uninstall    # tear down the launchd plist (idempotent)
        brew uninstall mcp-gateway
        rm -rf ~/.mcp-gateway            # optional: delete config + logs

      Skipping `service uninstall` first will leave a launchd plist on disk
      that respawns the now-missing binary on a loop until you remove
      ~/Library/LaunchAgents/com.ayu5h-raj.mcp-gateway.plist by hand.
    EOS
  end

  test do
    assert_match "mcp-gateway", shell_output("#{bin}/mcp-gateway --version")
  end
end
